# Generated by Django 6.0.3 on 2026-04-07 23:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaugeageJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jaugeage', models.DateField(verbose_name='Date du jaugeage')),
                ('type_jaugeage', models.CharField(choices=[('AVR', 'Avant'), ('APR', 'Après'), ('J', 'Jaugeage normal')], default='J', max_length=10, verbose_name='Type de jaugeage')),
                ('heure_jaugeage', models.TimeField(blank=True, help_text='Permet de différencier plusieurs jaugeages le même jour', null=True, verbose_name='Heure du jaugeage')),
                ('depot', models.CharField(default='SGDS SANKE', max_length=100, verbose_name='Dépôt')),
                ('type_depot', models.CharField(default='Dépôt de droit', max_length=50, verbose_name='Type de dépôt')),
                ('temperature_reference', models.DecimalField(decimal_places=1, default=Decimal('15.0'), max_digits=4, verbose_name='Température de référence (°C)')),
                ('operateur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opérateur')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jaugeage',
                'verbose_name_plural': 'Jaugeages',
                'ordering': ['-date_jaugeage', '-heure_jaugeage', '-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('date_jaugeage', 'type_jaugeage', 'heure_jaugeage'), name='unique_jaugeage_date_type_heure')],
            },
        ),
        migrations.CreateModel(
            name='ParametreJaugeageCuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hauteur_totale_temoin', models.IntegerField(help_text='Hauteur de référence de la cuve en millimètres (ex: 12981)', verbose_name='Hauteur Totale Témoin - HTT (mm)')),
                ('hauteur_min_livraison', models.IntegerField(default=2000, verbose_name='Hauteur minimale de livraison - Hml (mm)')),
                ('correction_creux', models.IntegerField(default=4, help_text='Correction systématique appliquée au creux mesuré (CONV_ADAMA L2)', verbose_name='Correction du creux mesuré (mm)')),
                ('remplissage_maxi', models.DecimalField(decimal_places=2, help_text='Volume maximum autorisé en exploitation', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remplissage maximum (litres)')),
                ('v_a', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='V(A) - Volume certificat hauteur décimal (litres)')),
                ('v_mn', models.IntegerField(verbose_name='V/mn - Volume par millimètre (litres/mm)')),
                ('reference_certificat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence du certificat')),
                ('date_certificat', models.DateField(blank=True, null=True, verbose_name='Date du certificat')),
                ('organisme_certificateur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisme certificateur')),
                ('date_prochain_jaugeage', models.DateField(blank=True, null=True, verbose_name='Date du prochain re-jaugeage')),
                ('is_pompe', models.BooleanField(default=False, help_text='True pour P GO, P SP', verbose_name='Est une pompe (index)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cuve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametre_jaugeage', to='SGDS.cuve', verbose_name='Cuve')),
            ],
            options={
                'verbose_name': 'Paramètre de jaugeage de cuve',
                'verbose_name_plural': 'Paramètres de jaugeage des cuves',
            },
        ),
        migrations.CreateModel(
            name='MesureCuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creux_mesure', models.IntegerField(blank=True, null=True, verbose_name='Creux mesuré (mm)')),
                ('t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température t1 (5/6 h)')),
                ('t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température t2 (1/2 h)')),
                ('t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température t3 (1/6 h)')),
                ('temperature_obs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température observée sur densité (°C)')),
                ('densite_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité moyenne mesurée')),
                ('densite_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité standard à 15°C (D15°C)')),
                ('facteur_vcf', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Facteur de correction de volume (Vcf)')),
                ('volume_additionnel', models.IntegerField(default=0, verbose_name='Volume ambiant additionnel (litres)')),
                ('volume_tuyauterie', models.IntegerField(default=0, verbose_name='Volume tuyauterie (litres)')),
                ('volume_eau', models.IntegerField(default=0, verbose_name='Volume eau (litres)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='SGDS.cuve', verbose_name='Cuve')),
                ('jaugeage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='SGDS.jaugeagejour', verbose_name='Jaugeage')),
            ],
            options={
                'verbose_name': 'Mesure de cuve',
                'verbose_name_plural': 'Mesures des cuves',
                'ordering': ['cuve__numero'],
                'constraints': [models.UniqueConstraint(fields=('jaugeage', 'cuve'), name='unique_mesure_jaugeage_cuve')],
            },
        ),
    ]
