# Generated by Django 6.0.3 on 2026-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0002_jaugeagejour_parametrejaugeagecuve_mesurecuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurecuve',
            name='v_a_saisi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume lu dans le cahier de jaugeage pour la hauteur décimale du jour', max_digits=12, null=True, verbose_name='V(A) certificat (litres)'),
        ),
    ]
