# Generated by Django 6.0.3 on 2026-04-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0004_jaugeagejour_date_validation_jaugeagejour_est_valide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION', 'Cession'), ('ACQUITTEMENT', 'Acquittement')], max_length=15, verbose_name='Type de mouvement')),
                ('regime_douanier', models.CharField(choices=[('ACQUITTE', 'Acquitté'), ('SOUS_DOUANE', 'Sous douane')], max_length=15, verbose_name='Régime douanier')),
                ('numero_enregistrement', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="N° d'enregistrement")),
                ('date_mouvement', models.DateField(verbose_name='Date du mouvement')),
                ('collaborateur', models.CharField(blank=True, max_length=150, null=True, verbose_name='Collaborateur (saisie)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Observations')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provenance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provenance (dépôt expéditeur)')),
                ('bl_expediteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° BL Dépôt Chargeur')),
                ('bl_client', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° BL Client')),
                ('date_chargement', models.DateField(blank=True, null=True, verbose_name='Date de chargement')),
                ('date_dechargement', models.DateField(blank=True, null=True, verbose_name='Date de déchargement')),
                ('volume_ambiant_expediteur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume ambiant expéditeur (L)')),
                ('volume_15c_expediteur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume @15°C expéditeur (L)')),
                ('densite_15c_expediteur', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité @15°C expéditeur (kg/m³)')),
                ('temperature_chargement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température au chargement (°C)')),
                ('volume_ambiant_recu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume ambiant reçu (L)')),
                ('temperature_reception', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température à la réception (°C)')),
                ('temperature_labo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température labo (°C)')),
                ('densite_observee_labo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité observée labo (kg/m³)')),
                ('densite_15c_calculee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité @15°C calculée (kg/m³)')),
                ('coefficient_conversion_15c', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Coefficient Vcf @15°C')),
                ('volume_15c_recu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume @15°C reçu (L)')),
                ('perte_gain_reception', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perte / Gain réception (L ambiant)')),
                ('perte_gain_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perte / Gain @15°C (L)')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Poids (kg)')),
                ('reference_client_externe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence client externe')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('code_destination', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code destination')),
                ('date_permis', models.DateField(blank=True, null=True, verbose_name='Date du permis douanier')),
                ('numero_permis_sortie', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Permis')),
                ('numero_s', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° S')),
                ('numero_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° C')),
                ('volume_ambiant_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume ambiant sortie (L)')),
                ('densite_15c_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densité @15°C sortie (kg/m³)')),
                ('temperature_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température sortie (°C)')),
                ('coefficient_conversion_sortie', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Coefficient Vcf sortie')),
                ('volume_15c_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume @15°C sortie (L)')),
                ('poids_sortie_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Poids sortie (kg)')),
                ('mode_reglement', models.CharField(blank=True, choices=[('ESP-IMMEDIAT', 'Espèces (immédiat)'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit')], max_length=20, null=True, verbose_name='Mode de règlement')),
                ('cession_volume_ambiant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume ambiant cédé (L)')),
                ('cession_volume_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume @15°C cédé (L)')),
                ('cession_motif', models.CharField(blank=True, max_length=300, null=True, verbose_name='Motif de la cession')),
                ('acquittement_volume_ambiant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume ambiant à acquitter (L)')),
                ('acquittement_volume_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume @15°C à acquitter (L)')),
                ('acquittement_reference_declaration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence déclaration douanière')),
                ('acquittement_date_declaration', models.DateField(blank=True, null=True, verbose_name='Date de la déclaration douanière')),
                ('acquittement_montant_droits', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant droits et taxes (FCFA)')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='SGDS.camion', verbose_name='Camion citerne')),
                ('cession_marketeur_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_recues', to='SGDS.marketeur', verbose_name='Marketeur destinataire (cession)')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='SGDS.chauffeur', verbose_name='Chauffeur')),
                ('cuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='SGDS.cuve', verbose_name='Cuve affectée')),
                ('marketeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='SGDS.marketeur', verbose_name='Marketeur (propriétaire)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='SGDS.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-date_mouvement', '-date_saisie'],
                'indexes': [models.Index(fields=['type_mouvement', 'date_mouvement'], name='SGDS_mouvem_type_mo_bc6042_idx'), models.Index(fields=['marketeur', 'date_mouvement'], name='SGDS_mouvem_markete_0852b0_idx'), models.Index(fields=['regime_douanier', 'date_mouvement'], name='SGDS_mouvem_regime__01f124_idx'), models.Index(fields=['marketeur', 'regime_douanier', 'produit'], name='SGDS_mouvem_markete_7ab903_idx')],
            },
        ),
    ]
