# Generated by Django 6.0.3 on 2026-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0005_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='numero_enregistrement',
            field=models.CharField(blank=True, editable=False, help_text='Généré automatiquement à la création (ex: ENT-2026-0001)', max_length=100, null=True, unique=True, verbose_name="N° d'enregistrement"),
        ),
    ]
