# Generated by Django 6.0.3 on 2026-04-12 20:11
# Data migration : attribue un numero_enregistrement conforme
# (format PREFIXE-ANNEE-SEQUENCE) à tous les mouvements existants
# qui n'en ont pas ou dont le format ne correspond pas.

from django.db import migrations


PREFIXES = {
    'ENTREE':       'ENT',
    'SORTIE':       'SOR',
    'CESSION':      'CES',
    'ACQUITTEMENT': 'ACQ',
}


def attribuer_numeros(apps, schema_editor):
    Mouvement = apps.get_model('SGDS', 'Mouvement')
    # Compteurs indépendants par (type, annee)
    compteurs = {}

    # Ordre chronologique pour respecter la séquence naturelle
    for m in Mouvement.objects.order_by('date_mouvement', 'date_saisie', 'pk'):
        # Saute les mouvements qui ont déjà un numéro au bon format
        if (m.numero_enregistrement
                and m.numero_enregistrement.startswith(tuple(PREFIXES.values()))
                and '-' in m.numero_enregistrement):
            # Mettre à jour le compteur interne pour ne pas créer de doublons
            try:
                parts = m.numero_enregistrement.split('-')
                annee = int(parts[1])
                seq   = int(parts[2])
                cle   = (m.type_mouvement, annee)
                compteurs[cle] = max(compteurs.get(cle, 0), seq)
            except (ValueError, IndexError):
                pass
            continue

        annee = m.date_mouvement.year if m.date_mouvement else 2026
        cle   = (m.type_mouvement, annee)
        compteurs[cle] = compteurs.get(cle, 0) + 1
        prefixe = PREFIXES.get(m.type_mouvement, 'MVT')
        m.numero_enregistrement = f"{prefixe}-{annee}-{compteurs[cle]:04d}"
        m.save(update_fields=['numero_enregistrement'])


def defaire_numeros(apps, schema_editor):
    # Pas de rollback possible sur les numéros (règle comptable)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0006_numero_enregistrement_auto'),
    ]

    operations = [
        migrations.RunPython(attribuer_numeros, defaire_numeros),
    ]
