# Generated by Django 6.0.3 on 2026-04-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0007_attribuer_numeros_mouvements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='acquittement_montant_droits',
        ),
    ]
