# Generated by Django 6.0.3 on 2026-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0008_suppr_acquittement_montant_droits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='ecart_densite_15c',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='(D15°C calculée labo − D15°C expéditeur BL) / 1000. Colonne AH Excel ENTREE. Alerte si |écart| > 0.001.', max_digits=8, null=True, verbose_name='Écart densité 15°C (calc − expé) / 1000'),
        ),
    ]
