# Generated by Django 6.0.3 on 2026-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0009_ajout_ecart_densite_15c'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_maj_stock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour du stock'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mis à jour automatiquement après validation du jaugeage', max_digits=14, verbose_name='Stock actuel (L)'),
        ),
    ]
