# Generated by Django 6.0.3 on 2026-04-18 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0010_ajout_stock_actuel_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresCoulage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateField(unique=True, verbose_name="Date d'application")),
                ('prix_unitaire_passage', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Prix unitaire de passage (FCFA/L)')),
                ('motif_defaut', models.CharField(default='Chargement', max_length=200, verbose_name='Motif par défaut')),
            ],
            options={
                'verbose_name': 'Paramètres de coulage',
                'verbose_name_plural': 'Paramètres de coulage',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=10, verbose_name='Statut')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_cloturees', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par')),
            ],
            options={
                'verbose_name': 'Période comptable',
                'verbose_name_plural': 'Périodes comptables',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='ClotureCoulageMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient_go', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('coefficient_super', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('pertes_gains_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pertes_gains_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumul_entree_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumul_entree_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumul_sortie_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumul_sortie_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prix_unitaire_passage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_coulage', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par')),
                ('periode', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cloture_coulage', to='SGDS.periodecomptable', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Clôture coulage mensuel',
                'verbose_name_plural': 'Clôtures coulage mensuel',
            },
        ),
        migrations.CreateModel(
            name='StockOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ambiant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume ambiant (L)')),
                ('volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume @15°C (L)')),
                ('calcul_auto', models.BooleanField(default=True, help_text='Si False, la valeur a été saisie manuellement et ne sera pas écrasée', verbose_name='Calcul automatique')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ouverture', to='SGDS.periodecomptable', verbose_name='Période')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Stock d'ouverture",
                'verbose_name_plural': "Stocks d'ouverture",
            },
        ),
        migrations.CreateModel(
            name='StockOuvertureCuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ambiant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume ambiant (L)')),
                ('volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume @15°C (L)')),
                ('calcul_auto', models.BooleanField(default=True, verbose_name='Calcul automatique')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.cuve', verbose_name='Cuve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ouverture_cuve', to='SGDS.periodecomptable', verbose_name='Période')),
                ('source_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGDS.mesurecuve', verbose_name='Mesure source')),
            ],
            options={
                'verbose_name': "Stock d'ouverture par cuve",
                'verbose_name_plural': "Stocks d'ouverture par cuve",
            },
        ),
        migrations.CreateModel(
            name='ClotureCoulageLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brut_entree_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coul_entree_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entree_nette_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sortie_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_qp_coul_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coef_qp_coul_go', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('qp_coul_go', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('brut_entree_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coul_entree_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entree_nette_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sortie_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_qp_coul_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coef_qp_coul_super', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('qp_coul_super', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('volume_global_sorti', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('marketeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.marketeur', verbose_name='Marketeur')),
                ('cloture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='SGDS.cloturecoulagemensuel', verbose_name='Clôture')),
            ],
            options={
                'verbose_name': 'Ligne coulage',
                'verbose_name_plural': 'Lignes coulage',
                'constraints': [models.UniqueConstraint(fields=('cloture', 'marketeur'), name='unique_cloture_ligne_marketeur')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodecomptable',
            constraint=models.UniqueConstraint(fields=('mois', 'annee'), name='unique_periode_mois_annee'),
        ),
        migrations.AddConstraint(
            model_name='stockouverture',
            constraint=models.UniqueConstraint(fields=('periode', 'produit'), name='unique_stock_ouv_periode_produit'),
        ),
        migrations.AddConstraint(
            model_name='stockouverturecuve',
            constraint=models.UniqueConstraint(fields=('periode', 'cuve'), name='unique_stock_ouv_periode_cuve'),
        ),
    ]
