# Generated by Django 6.0.3 on 2026-04-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0011_coulage_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodecomptable',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture"),
        ),
    ]
