# Generated by Django 6.0.3 on 2026-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0013_refactor_coulage_par_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_passage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tarif spécifique à ce produit. Laissez vide pour utiliser le tarif global (ParametresCoulage).', max_digits=10, null=True, verbose_name='Frais de passage (FCFA/L)'),
        ),
    ]
