# Generated by Django 6.0.3 on 2026-05-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0021_mouvement_entree_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION_EMISE', 'Cession émise'), ('CESSION_RECUE', 'Cession reçue'), ('ACQUITTEMENT', 'Acquittement')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('marketeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SGDS.marketeur')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SGDS.mouvement')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
