# Generated by Django 6.0.3 on 2026-05-17 11:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0022_notification_marketeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION_EMISE', 'Cession émise'), ('CESSION_RECUE', 'Cession reçue'), ('ACQUITTEMENT', 'Acquittement'), ('DOCUMENT_AJOUTE', 'Document ajouté'), ('ETAT_MENSUEL_DISPONIBLE', 'État mensuel disponible')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricalMouvementDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fichier', models.TextField(max_length=100, verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('BL_EXPEDITEUR', 'BL Expéditeur'), ('BL_CLIENT', 'BL Client'), ('PERMIS_SORTIE', 'Permis de Sortie'), ('BON_LIVRAISON', 'Bon de Livraison'), ('ORDRE_CESSION', 'Ordre de Cession'), ('DECLARATION_DOUANE', 'Déclaration Douanière'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('date_upload', models.DateTimeField(blank=True, editable=False, verbose_name="Date d'upload")),
                ('taille_fichier', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='SGDS.mouvement', verbose_name='Mouvement')),
                ('uploader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'historical Document justificatif',
                'verbose_name_plural': 'historical Documents justificatifs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MouvementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='mouvements/documents/%Y/%m/', verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('BL_EXPEDITEUR', 'BL Expéditeur'), ('BL_CLIENT', 'BL Client'), ('PERMIS_SORTIE', 'Permis de Sortie'), ('BON_LIVRAISON', 'Bon de Livraison'), ('ORDRE_CESSION', 'Ordre de Cession'), ('DECLARATION_DOUANE', 'Déclaration Douanière'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('taille_fichier', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='SGDS.mouvement', verbose_name='Mouvement')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document justificatif',
                'verbose_name_plural': 'Documents justificatifs',
                'ordering': ['-date_upload'],
            },
        ),
    ]
