# Generated by Django 6.0.3 on 2026-06-16 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0029_inventaire_initial_calcul_15c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerteGainInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_douanier', models.CharField(choices=[('ACQUITTE', 'Acquitté'), ('SOUS_DOUANE', 'Sous douane')], default='ACQUITTE', max_length=15, verbose_name='Régime douanier')),
                ('volume_ambiant', models.DecimalField(decimal_places=2, default=0, help_text='Positif = gain, négatif = perte', max_digits=12, verbose_name='Volume ambiant P/G (L)')),
                ('volume_15c', models.DecimalField(decimal_places=2, default=0, help_text='Positif = gain, négatif = perte', max_digits=12, verbose_name='Volume @15°C P/G (L)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Perte/Gain installation',
                'verbose_name_plural': 'Pertes/Gains installation',
                'ordering': ['-periode__annee', '-periode__mois', 'produit__nom'],
            },
        ),
        migrations.CreateModel(
            name='StockCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_douanier', models.CharField(choices=[('ACQUITTE', 'Acquitté'), ('SOUS_DOUANE', 'Sous douane')], default='ACQUITTE', max_length=15, verbose_name='Régime douanier')),
                ('volume_ambiant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume ambiant clôture (L)')),
                ('volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume @15°C clôture (L)')),
                ('calcul_auto', models.BooleanField(default=True, help_text='Si False, valeur saisie ou corrigée manuellement', verbose_name='Calcul automatique')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock de clôture',
                'verbose_name_plural': 'Stocks de clôture',
                'ordering': ['-periode__annee', '-periode__mois', 'produit__nom'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalmouvementdocument',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmouvementdocument',
            name='mouvement',
        ),
        migrations.RemoveField(
            model_name='historicalmouvementdocument',
            name='uploader',
        ),
        migrations.RemoveConstraint(
            model_name='stockouverture',
            name='unique_stock_ouv_periode_produit',
        ),
        migrations.AddField(
            model_name='stockouverture',
            name='regime_douanier',
            field=models.CharField(choices=[('ACQUITTE', 'Acquitté'), ('SOUS_DOUANE', 'Sous douane')], default='ACQUITTE', help_text='SD = Sous douane | Acquittée = produit acquitté en douane', max_length=15, verbose_name='Régime douanier'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='jaugeagejour',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='marketeur',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION', 'Cession'), ('ACQUITTEMENT', 'Acquittement'), ('RECLASSEMENT', 'Reclassement SD → Acquittée')], max_length=15, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='marketeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SGDS.marketeur', verbose_name='Marketeur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SGDS.mouvement', verbose_name='Mouvement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION_EMISE', 'Cession émise'), ('CESSION_RECUE', 'Cession reçue'), ('ACQUITTEMENT', 'Acquittement'), ('DOCUMENT_AJOUTE', 'Document ajouté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parametrejaugeagecuve',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='periodecomptable',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AddConstraint(
            model_name='stockouverture',
            constraint=models.UniqueConstraint(fields=('periode', 'produit', 'regime_douanier'), name='unique_stock_ouv_periode_produit_regime'),
        ),
        migrations.AddField(
            model_name='pertegaininstallation',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertes_gains_installation', to='SGDS.periodecomptable', verbose_name='Période'),
        ),
        migrations.AddField(
            model_name='pertegaininstallation',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='pertegaininstallation',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertes_gains_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='stockcloture',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_cloture', to='SGDS.periodecomptable', verbose_name='Période'),
        ),
        migrations.AddField(
            model_name='stockcloture',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.produit', verbose_name='Produit'),
        ),
        migrations.DeleteModel(
            name='HistoricalMouvementDocument',
        ),
        migrations.AddConstraint(
            model_name='pertegaininstallation',
            constraint=models.UniqueConstraint(fields=('periode', 'produit', 'regime_douanier'), name='unique_pg_installation_periode_produit_regime'),
        ),
        migrations.AddConstraint(
            model_name='stockcloture',
            constraint=models.UniqueConstraint(fields=('periode', 'produit', 'regime_douanier'), name='unique_stock_cloture_periode_produit_regime'),
        ),
    ]
