# Generated by Django 6.0.3 on 2026-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0030_add_regime_douanier_perte_gain_stock_cloture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CESSION_EMISE', 'Cession émise'), ('CESSION_RECUE', 'Cession reçue'), ('ACQUITTEMENT', 'Acquittement'), ('DOCUMENT_AJOUTE', 'Document ajouté'), ('ETAT_MENSUEL_DISPONIBLE', 'État mensuel disponible')], max_length=30),
        ),
    ]
