# Generated by Django 6.0.3 on 2026-06-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0032_exercice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOuvertureMarketeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_douanier', models.CharField(choices=[('ACQUITTE', 'Acquitté'), ('SOUS_DOUANE', 'Sous douane')], default='ACQUITTE', help_text='SD = Sous douane | Acquittée = produit acquitté en douane', max_length=15, verbose_name='Régime douanier')),
                ('volume_ambiant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume ambiant (L)')),
                ('volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume @15°C (L)')),
                ('calcul_auto', models.BooleanField(default=True, help_text='Si False, la valeur a été saisie manuellement et ne sera pas écrasée', verbose_name='Calcul automatique')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('marketeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ouverture', to='SGDS.marketeur', verbose_name='Marketeur')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ouverture_marketeur', to='SGDS.periodecomptable', verbose_name='Période')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGDS.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Stock d'ouverture marketeur",
                'verbose_name_plural': "Stocks d'ouverture marketeur",
                'constraints': [models.UniqueConstraint(fields=('periode', 'marketeur', 'produit', 'regime_douanier'), name='unique_stock_ouv_mkt_periode_marketeur_produit_regime')],
            },
        ),
    ]
