# Generated by Django 6.0.3 on 2026-06-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0033_stockouverturemarketeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False, verbose_name="Envoi d'emails activé")),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP (host)')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
                ('host_user', models.CharField(blank=True, max_length=255, verbose_name='Utilisateur SMTP (adresse email)')),
                ('host_password', models.CharField(blank=True, max_length=255, verbose_name="Mot de passe / mot de passe d'application")),
                ('default_from_email', models.CharField(blank=True, max_length=255, verbose_name="Adresse d'expédition par défaut")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configuration email',
            },
        ),
    ]
