# Generated by Django 6.0.3 on 2026-06-22 20:36

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def creer_depot_principal(apps, schema_editor):
    """Crée le dépôt 'PRINCIPAL' à partir des infos de site actuellement
    portées par la fiche Societe (singleton), avant que ces champs ne soient
    supprimés de Societe par cette même migration."""
    Societe = apps.get_model('SGDS', 'Societe')
    Depot = apps.get_model('SGDS', 'Depot')

    societe = Societe.objects.filter(pk=1).first()
    if Depot.objects.exists():
        return

    Depot.objects.create(
        code='PRINCIPAL',
        nom=getattr(societe, 'nom_depot', None) or 'SGDS SANKE',
        type_depot=getattr(societe, 'type_depot', None) or 'Dépôt de droit',
        numero_agrement=getattr(societe, 'numero_agrement', None),
        autorite_tutelle=getattr(societe, 'autorite_tutelle', None),
        date_creation=getattr(societe, 'date_creation', None),
        adresse=getattr(societe, 'adresse', None),
        ville=getattr(societe, 'ville', None),
        telephone=getattr(societe, 'telephone', None),
        statut='ACTIF',
        slug=slugify('PRINCIPAL'),
    )


def supprimer_depot_principal(apps, schema_editor):
    Depot = apps.get_model('SGDS', 'Depot')
    Depot.objects.filter(code='PRINCIPAL').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0034_configuration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code dépôt')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du dépôt')),
                ('type_depot', models.CharField(default='Dépôt de droit', max_length=100, verbose_name='Type de dépôt')),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Agrément')),
                ('autorite_tutelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autorité de tutelle')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du dépôt')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'ordering': ['nom'],
            },
        ),
        migrations.RunPython(creer_depot_principal, supprimer_depot_principal),
        migrations.AlterModelOptions(
            name='societe',
            options={'verbose_name': 'Société', 'verbose_name_plural': 'Société'},
        ),
        migrations.RemoveField(
            model_name='societe',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='autorite_tutelle',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='nom_depot',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='numero_agrement',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='telephone2',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='type_depot',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='ville',
        ),
    ]
