# Generated by Django 6.0.3 on 2026-06-22 20:47 (édité à la main : depot sur
# JaugeageJour passe d'un CharField texte à une vraie ForeignKey — un ALTER
# direct échoue côté Postgres car les anciennes valeurs ('SGDS SANKE', ...)
# ne sont pas castables en bigint, donc on supprime puis on recrée le champ).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0035_depot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventaireinitialmarketeur',
            name='unique_inventaire_initial_mktr_prod_regime',
        ),
        migrations.RemoveConstraint(
            model_name='jaugeagejour',
            name='unique_jaugeage_date_type_heure',
        ),
        migrations.RemoveConstraint(
            model_name='periodecomptable',
            name='unique_periode_mois_annee',
        ),
        migrations.RemoveField(
            model_name='jaugeagejour',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='jaugeagejour',
            name='type_depot',
        ),
        migrations.AddField(
            model_name='cuve',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuves', to='SGDS.depot', verbose_name='Dépôt'),
        ),
        migrations.AddField(
            model_name='inventaireinitialmarketeur',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_initiaux', to='SGDS.depot', verbose_name='Dépôt'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='SGDS.depot', verbose_name='Dépôt'),
        ),
        migrations.AddField(
            model_name='periodecomptable',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodes_comptables', to='SGDS.depot', verbose_name='Dépôt'),
        ),
        migrations.AddField(
            model_name='jaugeagejour',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jaugeages', to='SGDS.depot', verbose_name='Dépôt'),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Numéro de cuve'),
        ),
        migrations.AlterField(
            model_name='periodecomptable',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(fields=('depot', 'numero'), name='unique_cuve_depot_numero'),
        ),
        migrations.AddConstraint(
            model_name='inventaireinitialmarketeur',
            constraint=models.UniqueConstraint(fields=('depot', 'marketeur', 'produit', 'regime_douanier'), name='unique_inventaire_initial_depot_mktr_prod_regime'),
        ),
        migrations.AddConstraint(
            model_name='jaugeagejour',
            constraint=models.UniqueConstraint(fields=('depot', 'date_jaugeage', 'type_jaugeage', 'heure_jaugeage'), name='unique_jaugeage_depot_date_type_heure'),
        ),
        migrations.AddConstraint(
            model_name='periodecomptable',
            constraint=models.UniqueConstraint(fields=('depot', 'mois', 'annee'), name='unique_periode_depot_mois_annee'),
        ),
    ]
