# Generated by Django 6.0.3 on 2026-06-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0041_exercice_depot_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleEmailEtatMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(default='[SGDS] Vos états mensuels {{ periode }} sont disponibles', max_length=255, verbose_name="Sujet de l'email")),
                ('corps', models.TextField(default="Bonjour,\n\nLes états mensuels de {{ societe }} pour la période {{ periode }} sont disponibles.\nVous trouverez ci-joint, en pièces jointes Excel et PDF, le stock d'ouverture/fermeture, la répartition du coulage et les frais de passage de {{ marketeur }}.\n\nCordialement.", verbose_name="Corps de l'email")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Gabarit email — états mensuels',
                'verbose_name_plural': 'Gabarit email — états mensuels',
            },
        ),
        migrations.CreateModel(
            name='EnvoiEtatMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinataire', models.CharField(blank=True, max_length=255, verbose_name='Email destinataire')),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], max_length=10, verbose_name='Statut')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('declenche_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Déclenché par')),
                ('marketeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois_etat_mensuel', to='SGDS.marketeur', verbose_name='Marketeur')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois_etat_mensuel', to='SGDS.periodecomptable', verbose_name='Période')),
            ],
            options={
                'verbose_name': "Envoi d'état mensuel",
                'verbose_name_plural': "Envois d'états mensuels",
                'ordering': ['-date_envoi'],
            },
        ),
    ]
