# Generated by Django 6.0.3 on 2026-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0042_modele_email_envoi_etat_mensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleEmailMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(default='[SGDS] {{ type_mouvement }} — {{ produit }} — N° {{ numero }}', max_length=255, verbose_name="Sujet de l'email")),
                ('corps', models.TextField(default="Bonjour,\n\nUne opération de type {{ type_mouvement }} a été enregistrée pour {{ marketeur }} :\nProduit : {{ produit }}\nVolume : {{ volume }} L @15°C\nDate : {{ date_mouvement }}\nN° d'enregistrement : {{ numero }}\n\nVeuillez trouver ci-joint le document de ce mouvement.\n\nCordialement.", verbose_name="Corps de l'email")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Gabarit email — mouvements',
                'verbose_name_plural': 'Gabarit email — mouvements',
            },
        ),
        migrations.AlterField(
            model_name='modeleemailetatmensuel',
            name='corps',
            field=models.TextField(default='Bonjour,\n\nLes états mensuels de {{ societe }} pour la période {{ periode }} sont disponibles.\nVous trouverez ci-joint, en Excel et en PDF (un fichier par état), le Stock Ouverture, le Stock Fermeture, la Répartition du coulage, le Stock à 15°, le Stock Ambiant et les Frais de passage de {{ marketeur }}.\n\nCordialement.', verbose_name="Corps de l'email"),
        ),
    ]
