# Generated by Django 6.0.3 on 2026-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0043_modeleemailmouvement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleemailmouvement',
            name='corps',
            field=models.TextField(default="Bonjour,\n\nUne opération de type {{ type_mouvement }} a été enregistrée pour {{ marketeur }} :\nProduit : {{ produit }}\nVolume : {{ volume }} L @15°C\nDate : {{ date_mouvement }}\nN° d'enregistrement : {{ numero }}\n\n{% if is_entree %}DONNÉES D'ENTRÉE\nDate de chargement : {{ date_chargement }}\nN° BL Dépôt Chargeur : {{ bl_chargeur }}\nVol. ambiant expéditeur (L) : {{ vol_amb_expediteur }}\nDONNÉES OBTENUES À LA RÉCEPTION\nVol. ambiant reçu (L) : {{ vol_amb_recu }}\n\n{% elif is_sortie %}DONNÉES DE SORTIE\nRéférence client externe : {{ reference_client }}\nDestination : {{ destination }}\nVol. ambiant sortie (L) : {{ vol_amb_sortie }}\n\n{% elif is_cession %}DONNÉES DE CESSION\nMarketeur source (cédant) : {{ marketeur_cedant }}\nMarketeur destinataire : {{ marketeur_destinataire }}\nVol. ambiant cédé (L) : {{ vol_amb_cede }}\nMotif de la cession : {{ motif_cession }}\nN° autorisation Direction : {{ numero_autorisation }}\nDate autorisation : {{ date_autorisation }}\n\n{% elif is_acquittement %}DONNÉES D'ACQUITTEMENT\nEntrée Sous douane associée (N° BL Dépôt Chargeur) : {{ bl_chargeur_source }}\nVolume à acquitter (L) : {{ vol_a_acquitter }}\nRéférence déclaration douanière : {{ reference_declaration }}\nDate de la déclaration : {{ date_declaration }}\n\n{% endif %}Veuillez trouver ci-joint le document de ce mouvement.\n\nCordialement.", verbose_name="Corps de l'email"),
        ),
    ]
