# Generated by Django 6.0.3 on 2026-04-24 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('CHEF_DEPOT', 'Chef de Dépôt'), ('OPERATEUR', 'Opérateur de Saisie'), ('COMPTABLE', 'Comptable'), ('LECTEUR', 'Lecteur (Lecture seule)')], default='LECTEUR', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('derniere_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_username_snapshot', models.CharField(blank=True, help_text='Snapshot du username au cas où le user est supprimé', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAILED', 'Connexion échouée'), ('EXPORT', 'Export'), ('VALIDATE', 'Validation'), ('CLOSE', 'Clôture'), ('OPEN', 'Ouverture')], db_index=True, max_length=15)),
                ('objet_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('objet_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('objet_repr', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('ADMIN', 'Admin'), ('SYSTEM', 'Système')], db_index=True, default='WEB', max_length=10)),
                ('changements', models.JSONField(blank=True, help_text='Dict {champ: {avant, apres}}', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['-horodatage', 'action'], name='users_audit_horodat_5dfab9_idx'), models.Index(fields=['user', '-horodatage'], name='users_audit_user_id_c60494_idx'), models.Index(fields=['objet_type', 'objet_id'], name='users_audit_objet_t_b55d7c_idx')],
            },
        ),
    ]
