# Generated by Django 6.0.3 on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Ajouter role_old pour conserver les codes legacy
        migrations.AddField(
            model_name='userprofile',
            name='role_old',
            field=models.CharField(
                blank=True, null=True, max_length=20,
                verbose_name='Rôle (legacy)',
                choices=[
                    ('SUPERADMIN', 'Super Administrateur'),
                    ('CHEF_DEPOT', 'Chef de Dépôt'),
                    ('OPERATEUR', 'Opérateur de Saisie'),
                    ('COMPTABLE', 'Comptable'),
                    ('LECTEUR', 'Lecteur (Lecture seule)'),
                ],
            ),
        ),
        # 2. Copier les codes texte actuels dans role_old
        migrations.RunSQL(
            sql='UPDATE users_userprofile SET role_old = role',
            reverse_sql='UPDATE users_userprofile SET role = role_old',
        ),
        # 3. Créer le modèle Role
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(
                    help_text="Affiché dans l'interface (ex: 'Chef de Dépôt')",
                    max_length=100, unique=True, verbose_name='Nom du rôle',
                )),
                ('code', models.CharField(
                    help_text="Identifiant technique stable (ex: 'CHEF_DEPOT'). Ne peut pas être modifié après création.",
                    max_length=50, unique=True, verbose_name='Code interne',
                )),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('systeme', models.BooleanField(
                    default=False,
                    help_text='Si coché, le rôle ne peut pas être supprimé.',
                    verbose_name='Rôle système',
                )),
                ('couleur', models.CharField(
                    choices=[
                        ('red', 'Rouge'), ('orange', 'Orange'), ('yellow', 'Jaune'),
                        ('green', 'Vert'), ('blue', 'Bleu'), ('indigo', 'Indigo'),
                        ('purple', 'Violet'), ('pink', 'Rose'), ('gray', 'Gris'),
                    ],
                    default='gray',
                    help_text="Couleur du badge dans l'interface.",
                    max_length=20,
                )),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL,
                )),
                ('permissions', models.ManyToManyField(
                    blank=True, related_name='roles_sgds',
                    to='auth.permission', verbose_name='Permissions',
                )),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['-systeme', 'nom'],
            },
        ),
        # 4. Remplacer la colonne role (varchar) par role_id (bigint FK → Role)
        #    On utilise SeparateDatabaseAndState pour faire le DROP/ADD directement en SQL
        #    (évite les problèmes de cast ALTER COLUMN TYPE sur PostgreSQL)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE users_userprofile DROP COLUMN role;
                        ALTER TABLE users_userprofile
                            ADD COLUMN role_id bigint NULL
                            REFERENCES users_role(id)
                            ON DELETE RESTRICT
                            DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql="""
                        ALTER TABLE users_userprofile DROP COLUMN role_id;
                        ALTER TABLE users_userprofile
                            ADD COLUMN role character varying(20) NOT NULL DEFAULT 'LECTEUR';
                        UPDATE users_userprofile SET role = COALESCE(role_old, 'LECTEUR');
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='userprofile',
                    name='role',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='utilisateurs',
                        to='users.role',
                        verbose_name='Rôle',
                    ),
                ),
            ],
        ),
    ]
