# Generated by Django 6.0.3 on 2026-06-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0035_depot'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_seed_django_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-horodatage'], 'verbose_name': "Entree d'audit", 'verbose_name_plural': "Journal d'audit"},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-systeme', 'nom'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='depot',
            field=models.ForeignKey(blank=True, help_text="Depot auquel l'utilisateur est rattache. Laisser vide pour SUPERADMIN (acces global) ou MARKETEUR (transige avec plusieurs depots).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='SGDS.depot', verbose_name='Depot assigne'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Deconnexion'), ('LOGIN_FAILED', 'Connexion echouee'), ('EXPORT', 'Export'), ('VALIDATE', 'Validation'), ('CLOSE', 'Cloture'), ('OPEN', 'Ouverture')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('ADMIN', 'Admin'), ('SYSTEM', 'Systeme')], db_index=True, default='WEB', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_username_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot du username au cas ou le user est supprime', max_length=150),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text="Identifiant technique stable (ex: 'CHEF_DEPOT'). Ne peut pas etre modifie apres creation.", max_length=50, unique=True, verbose_name='Code interne'),
        ),
        migrations.AlterField(
            model_name='role',
            name='django_group',
            field=models.OneToOneField(blank=True, editable=False, help_text='Synchronise automatiquement. Ne pas modifier manuellement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_sgds', to='auth.group', verbose_name='Groupe Django natif'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(help_text="Affiche dans l'interface (ex: 'Chef de Depot')", max_length=100, unique=True, verbose_name='Nom du role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='systeme',
            field=models.BooleanField(default=False, help_text='Si coche, le role ne peut pas etre supprime.', verbose_name='Role systeme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role RBAC. Defaut : LECTEUR a la creation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='users.role', verbose_name='Role'),
        ),
    ]
