# Generated by Django 6.0.3 on 2026-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGDS', '0041_exercice_depot_required'),
        ('users', '0009_userprofile_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='depots',
            field=models.ManyToManyField(blank=True, help_text="Depots auxquels l'utilisateur est rattache (un ou plusieurs). Laisser vide pour SUPERADMIN (acces global) ou MARKETEUR (transige avec plusieurs depots).", related_name='utilisateurs_assignes', to='SGDS.depot', verbose_name='Depots assignes'),
        ),
    ]
